### ISSUE TITLE
Need to manually return to the main screen for the script to work

### ISSUE THREAD

**Issue by hyper-ape** [deli841/tg_reporter#3]
![image](https://user-images.githubusercontent.com/85020965/156174078-a55e21cf-a50f-4bc8-9825-8bae47929098.png)
Namely press this arrow each time, then it works. I guess a step is missing from the script, will try to look into it and fix myself but once again, FYI

**Comment by deli841** [comment]
Help will be appreciated!

**Comment by hyper-ape** [comment]
Submitted the fix, I guess you'll need to approve
